# Generated by Django 4.0.6 on 2022-07-28 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_remove_post_author_remove_post_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="ingredients",
            field=models.CharField(max_length=100),
        ),
    ]
