# Generated by Django 4.0.6 on 2022-07-29 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0004_alter_recipe_ingredients"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="difficulty_level",
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="ingredients",
            field=models.CharField(max_length=1000),
        ),
    ]
