# Generated by Django 4.0.6 on 2022-07-29 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0006_process"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Process",
            new_name="Review",
        ),
        migrations.AddField(
            model_name="recipe",
            name="process",
            field=models.TextField(default=0),
        ),
    ]
