# Generated by Django 4.0.6 on 2022-07-29 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0007_rename_process_review_recipe_process"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Tag",
        ),
        migrations.RemoveField(
            model_name="category",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="category",
            name="slug",
        ),
    ]
