# Generated by Django 4.0.6 on 2022-07-29 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0008_delete_tag_remove_category_parent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="recipes.category",
            ),
            preserve_default=False,
        ),
    ]
