# Generated by Django 4.0.6 on 2022-08-08 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0010_review_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="recipes/img"),
        ),
    ]
